begin;
select plan(28);
select has_schema('core');
select has_schema('lifecycle');
select has_schema('audit');
select has_schema('security');
select has_table('core','accounts');
select has_table('core','identities');
select has_table('core','participants');
select has_table('core','participations');
select has_table('core','contexts');
select has_table('core','roles');
select has_table('core','capabilities');
select has_table('core','authorization_decisions');
select has_table('lifecycle','states');
select has_table('lifecycle','transitions');
select has_table('lifecycle','transition_policies');
select has_table('lifecycle','transition_requests');
select has_table('lifecycle','lifecycle_bindings');
select has_table('lifecycle','reviews');
select has_table('lifecycle','verifications');
select has_table('lifecycle','state_history');
select has_table('lifecycle','transition_history');
select has_table('lifecycle','review_history');
select has_table('lifecycle','verification_history');
select has_table('core','credentials');
select has_table('audit','events');
select has_table('audit','evidence');
select has_table('audit','idempotency_keys');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='core' and c.relname='accounts'),'accounts RLS enabled');
select * from finish();
rollback;
