import { renderLegaXPage, type Section } from "./page";

type Surface={key:Section;eyebrow:string;title:string;description:string;flow:string[];capabilities:Array<[string,string]>};
const surfaces:Record<string,Surface>={
identity:{key:"Identity",eyebrow:"Identity",title:"Identity",description:"A canonical identity surface that keeps identity evidence, account state, participation and authority separate.",flow:["Evidence state","Identity record","Context","Permitted view"],capabilities:[["Evidence","Verified, declared, observed or unknown"],["Account","Authentication remains separate"],["Participation","Contextual, never universal"],["Privacy","Minimum necessary fields"]]},
people:{key:"People",eyebrow:"People & relationships",title:"People",description:"Discover people only inside an established context and permitted visibility boundary. A visible person is never automatically authorized.",flow:["Context selected","Authorized read","People records","Governed actions"],capabilities:[["Identity","Evidence-aware presentation"],["Participation","Scoped participation"],["Relationships","Community, organization, provider or service"],["Privacy","Field minimization"]]},
participation:{key:"Participation",eyebrow:"Context",title:"Participation & Context",description:"Context determines where a person, organization or provider is operating. Context never grants authority by itself.",flow:["Identity","Participation","Active context","Authorization"],capabilities:[["Context","Explicit active scope"],["Membership","Relationship, not permission"],["Scope","Place, organization or provider boundary"],["Revocation","State can become inactive"]]},
communities:{key:"Communities",eyebrow:"Community operations · 20A",title:"Communities",description:"A distinct community operating experience for community life, people, places, shared services and place-based operations.",flow:["Community","Place","Participation","Operation"],capabilities:[["People","Participants and relationships"],["Places","Places, units and facilities"],["Services","Community service requests"],["Operations","Incidents, maintenance and visitors"]]},
organizations:{key:"Organizations",eyebrow:"Organization operations · 20B",title:"Organizations",description:"A distinct organization operating experience for purpose, governance, teams, work, projects, policies, decisions and resources.",flow:["Organization","Governance","Decision","Authorized work"],capabilities:[["Governance","Decision records and policy"],["Teams","Responsibility and bounded work"],["Projects","Work portfolios and timelines"],["Assurance","Risk, evidence and review"]]},
providers:{key:"Providers",eyebrow:"Provider operations · 20C",title:"Providers",description:"A distinct provider operating experience for services, customers, workers, capacity, dispatch, delivery, commerce and quality.",flow:["Demand","Capacity","Dispatch","Delivery"],capabilities:[["Services","Provider service catalog"],["Workforce","Workers and credentials"],["Dispatch","Schedules and assignments"],["Quality","Evidence, incidents and reconciliation"]]},
places:{key:"Places",eyebrow:"Physical world",title:"Places",description:"The physical context of LegaX: communities, places, units, facilities and resources. Location is context, not authority.",flow:["Community","Place","Unit / facility","Resource state"],capabilities:[["Place","Physical context"],["Unit","Scoped occupancy relationship"],["Facility","Availability and operations"],["Resource","State and governed use"]]},
units:{key:"Units",eyebrow:"Physical context",title:"Units",description:"Units represent bounded physical spaces inside a place. Occupancy, relationship and ownership must never be conflated.",flow:["Place","Unit","Relationship","Permitted action"],capabilities:[["Occupancy","State, not ownership"],["Relationship","Resident or participant scope"],["Access","Authorization remains separate"],["Evidence","Source and state remain visible"]]},
resources:{key:"Resources",eyebrow:"Resources",title:"Resources",description:"Resources represent things that can be referenced or operated within governed context. Availability is not automatic assignability.",flow:["Resource","Context","Capability","Authorization"],capabilities:[["State","Available, reserved, occupied or unknown"],["Capability","What may be requested"],["Authorization","Server-side decision"],["Evidence","Operational provenance"]]},
services:{key:"LegaServices",eyebrow:"LegaServices",title:"LegaServices",description:"The service operating surface follows a service need through governed request, authorization, execution, outcome and evidence.",flow:["Service","Request","Authorization","Execution"],capabilities:[["Eligibility","Context and service rules"],["Capability","What the actor can request"],["Execution","Core execution only"],["Outcome","Never claim success without authority/evidence"]]},
access:{key:"Access",eyebrow:"Access",title:"Access",description:"Access is enforcement of an authorization decision. Identity evidence, credentials, context and authorization remain distinct.",flow:["Identity evidence","Verification","Context","Access decision"],capabilities:[["Credentials","Evidence-backed credentials"],["Assurance","Explicit assurance level"],["Decision","Authorization remains authoritative"],["Enforcement","Access is the enforcement layer"]]},
requests:{key:"Requests",eyebrow:"Requests & actions",title:"Requests & Actions",description:"A request can lead to an action only through the canonical command and authorization path. The interface never turns a button into authority.",flow:["Request","Eligibility","Authorization","Command / execution"],capabilities:[["Status","Pending, allowed, denied or unknown"],["Idempotency","Retries cannot duplicate execution"],["Execution","One canonical engine"],["Recovery","Unknown outcomes reconcile"]]},
activity:{key:"Activity",eyebrow:"Events & outcomes",title:"Activity",description:"Activity presents meaningful events and outcomes in human language first, with provenance and technical identifiers available progressively.",flow:["Action","Event","Outcome","Evidence"],capabilities:[["Timeline","Human-readable first"],["Provenance","Causation and correlation"],["Outcome","Authoritative state only"],["Recovery","Unknown and reconciliation visible"]]},
evidence:{key:"Evidence",eyebrow:"Evidence",title:"Evidence",description:"Evidence supports claims without silently becoming truth. Verification state, provenance, source and lifecycle remain visible.",flow:["Source","Capture","Verification","Claim support"],capabilities:[["Provenance","Who, what, when, where"],["State","Captured, submitted, verified or unknown"],["Privacy","Scoped access"],["Retention","Governed lifecycle"]]},
commerce:{key:"Commerce",eyebrow:"Economic & commerce",title:"Commerce",description:"Commerce surfaces requests, commitments, payment states and reconciliation without presenting initiation as settlement.",flow:["Offer / request","Commitment","Payment","Reconciliation"],capabilities:[["State","Initiated, pending, settled or unknown"],["Providers","External systems are adapters"],["Evidence","Payment/provider evidence"],["Reconciliation","Unknown is not success"]]},
account:{key:"Account",eyebrow:"Account",title:"Account",description:"Account is the authentication and account-management surface. It is not the identity authority, participation authority or execution engine.",flow:["Authentication","Account","Session","Context"],capabilities:[["Authentication","Sign-in state"],["Recovery","Account recovery"],["Profile","User-controlled account fields"],["Separation","Identity remains canonical"]]},
administration:{key:"Administration",eyebrow:"Administration",title:"Administration",description:"Administration is a governed management surface. Administrative UI cannot manufacture authority, bypass authorization or create a second execution system.",flow:["Scope","Policy / configuration","Authorization","Audited change"],capabilities:[["Governance","Bounded administrative scope"],["Policy","Explicit lifecycle"],["Audit","Events and evidence"],["Security","No client-side authority"]]}
};
const flowMarkup=(flow:string[])=>`<div class="flow" aria-label="Canonical surface flow">${flow.map((x,i)=>`<div class="flow-step"><small>0${i+1}</small><strong>${x}</strong></div>`).join("")}</div>`;

export function renderControlPlane(path:string):Response{
 const key=path.replace(/^\//,"").replace(/\/$/,"")||"overview";
 if(key==="overview") return renderOverview();
 const s=surfaces[key]; if(!s) return renderOverview();
 return renderLegaXPage({title:s.title,active:s.key,content:`
 <section class="page-hero"><p class="eyebrow">${s.eyebrow}</p><h1>${s.title}</h1><p class="lede">${s.description}</p></section>
 <section class="panel"><div class="panel-heading"><div><p class="kicker">Governed operating surface</p><h2>Canonical interaction boundary</h2></div><span class="state neutral">Context / authorization required</span></div>${flowMarkup(s.flow)}
 <div class="empty" role="status"><strong>No authoritative records are loaded into this surface.</strong><p>This is intentional. The interface populates only from a canonical read establishing context, permitted visibility and current domain state. It does not invent records, permissions or outcomes.</p></div></section>
 <section class="cap-grid" aria-label="${s.title} capabilities">${s.capabilities.map(([a,b])=>`<article class="cap"><strong>${a}</strong><span>${b}</span></article>`).join("")}</section>
 <section class="panel light-panel"><p class="kicker">Invariant</p><h2>UI presents authority; UI does not create authority.</h2><p>Consequential actions remain server-side governed. A hidden, visible, cached or client-generated control can never substitute for LegaX authorization.</p></section>`});
}

function renderOverview():Response{
 const cards:Array<[Section,string,string,string]>=[
 ["Identity","Identity","Evidence-aware identity without collapsing account, participation or authority.","/identity"],
 ["People","People","Governed relationships inside an established context.","/people"],
 ["Participation","Participation / Context","The active scope in which LegaX operates.","/participation"],
 ["Communities","Communities","20A community life and place-based operations.","/communities"],
 ["Organizations","Organizations","20B governance, work and organizational operations.","/organizations"],
 ["Providers","Providers","20C provider service delivery operations.","/providers"],
 ["Places","Places","Physical places, facilities and resources.","/places"],
 ["Units","Units","Bounded physical spaces with explicit relationships.","/units"],
 ["Resources","Resources","Resource state, capability and governed use.","/resources"],
 ["LegaServices","LegaServices","Service request through authorization, execution and evidence.","/services"],
 ["Access","Access","Authorization enforcement across physical and digital access.","/access"],
 ["Requests","Requests / Actions","Canonical requests and consequential command boundaries.","/requests"],
 ["Activity","Activity / Events","Human-readable events, outcomes and recovery.","/activity"],
 ["Evidence","Evidence","Provenance-backed support for claims and outcomes.","/evidence"],
 ["Commerce","Commerce","Economic state without false settlement claims.","/commerce"],
 ["Account","Account","Authentication and account management, kept separate from identity.","/account"],
 ["Administration","Administration","Governed configuration and operations without parallel authority.","/administration"]];
 return renderLegaXPage({title:"Welcome Home",active:"Overview",content:`
 <section class="hero" aria-labelledby="welcome"><img class="hero-logo" src="https://raw.githubusercontent.com/kyabutwa/LEGAX/main/legax-logo-transparent.png" alt="LegaX logo"><div class="eyebrow"><span class="dot" aria-hidden="true"></span> Living infrastructure</div><h1 id="welcome">Welcome Home<span class="fr">Bienvenue chez vous</span></h1><p class="lede">LegaX connects identity, participation, places, services, commerce and the physical world while keeping people and communities in control of what they authorize.</p></section>
 <section class="control-grid" aria-label="LegaX control plane">${cards.slice(0,6).map(([i,t,d,h])=>`<a class="control-card" href="${h}"><span class="index">${i.toUpperCase()}</span><h2>${t}</h2><p>${d}</p></a>`).join("")}</section>
 <section class="section-grid" aria-label="LegaX domains">${cards.slice(6).map(([i,t,d,h])=>`<a class="control-card section-card" href="${h}"><span class="index">${i.toUpperCase()}</span><strong>${t}</strong><span>${d}</span></a>`).join("")}</section>
 <div class="status-row" aria-label="Runtime state"><span>Canonical runtime foundation</span><span class="status-value">Operational foundation · governed UI</span></div>`});
}
