import { currentAccount, createAccount, signIn, signOut, authError, type AuthEnv } from "./auth";
import { renderLegaXPage } from "./ui/page";
import { renderAuthenticatedHome } from "./ui/authenticated-home";

const intents=["participant","join-community","community","provider","organization"];
function esc(v:string){return v.replace(/[&<>"']/g,function(c){return c==="&"?"&amp;":c==="<"?"&lt;":c===">"?"&gt;":c==='"'?"&quot;":"&#39;";});}
function intentOf(v:string|null){return intents.includes(v||"")?v||"":"";}
function selectedLabel(v:string){if(v==="participant")return "Join as a Participant";if(v==="join-community")return "Join a Community";if(v==="community")return "Join as a Community";if(v==="provider")return "Join as a Provider";if(v==="organization")return "Join as an Organization";return "Enter LegaX";}
async function redirectWithSession(response:Response,request:Request,env:AuthEnv,next:string){if(response.status!==303)return response;if(next==="/"){const setCookie=response.headers.get("set-cookie");const token=setCookie?.split(";")[0];if(token){const homeRequest=new Request(request.url,{headers:{cookie:token}});const account=await currentAccount(env,homeRequest);if(account){const home=renderAuthenticatedHome(account);const headers=new Headers(home.headers);headers.set("set-cookie",setCookie);headers.set("cache-control","no-store");return new Response(home.body,{status:200,headers});}}}const headers=new Headers(response.headers);headers.set("location",next);headers.set("cache-control","no-store");return new Response(null,{status:303,headers});}
export async function handleAccountEntry(request:Request,env:AuthEnv):Promise<Response>{
 const url=new URL(request.url),intent=intentOf(url.searchParams.get("intent"));
 try{
  if(request.method==="POST"){
   const form=await request.formData(),action=String(form.get("action")||""),chosen=intentOf(String(form.get("intent")||intent)),next=chosen?"/onboarding?intent="+encodeURIComponent(chosen):"/";
   if(action==="create")return redirectWithSession(await createAccount(env,{email:String(form.get("email")||""),password:String(form.get("password")||""),passwordConfirmation:String(form.get("password_confirmation")||""),displayName:String(form.get("display_name")||"")}),request,env,next);
   if(action==="signin")return redirectWithSession(await signIn(env,{email:String(form.get("email")||""),password:String(form.get("password")||"")}),request,env,next);
   if(action==="signout")return signOut(env,request);
  }
  return renderAccountEntry(await currentAccount(env,request),null,intent,url.searchParams.get("recovered")==="1");
 }catch(error){return renderAccountEntry(null,authError(error),intent,url.searchParams.get("recovered")==="1");}
}
function renderAccountEntry(account:any,error:string|null,intent:string,recovered=false):Response{
 const label=selectedLabel(intent);
 const recoveryNotice=recovered?"<section class=\"account-next\"><strong>Password reset complete</strong><span>Your active sessions were revoked. Sign in again with your new password.</span></section>":"";
 const content=account?"<section class=\"account-hero\"><p class=\"eyebrow\">Authenticated</p><h1>Your LegaX account</h1><p class=\"lede\">Your account and authenticated session are active. Continue into your LegaX home; choose a governed context there when you are ready.</p></section><section class=\"account-grid\"><article class=\"account-card\"><span class=\"kicker\">Signed in</span><strong>"+esc(String(account.display_name||"Account"))+"</strong><span>"+esc(String(account.account_id))+"</span><span>Identity verification: "+esc(String(account.verification_state))+"</span></article><article class=\"account-card\"><span class=\"kicker\">Security</span><strong>Session active</strong><span>HttpOnly secure session cookie</span><span>Password is stored as a derived credential.</span></article></section>"+recoveryNotice+"<section class=\"account-next\"><strong>Authenticated entry</strong><span>This account is the authentication foundation. It does not itself create participation or authorization.</span><a class=\"button primary\" href=\"/\">Open LegaX home</a><a class=\"button secondary\" href=\"/join\">Review governed entry paths</a></section><form method=\"post\" class=\"account-action\"><input type=\"hidden\" name=\"action\" value=\"signout\"><button type=\"submit\">Sign out</button></form>":
 "<section class=\"account-hero\"><p class=\"eyebrow\">LegaX entry</p><h1>"+esc(label)+"</h1><p class=\"lede\">One LegaX account can support many governed contexts. Choose the path you intend to enter.</p></section>"+(error?"<div class=\"auth-error\" role=\"alert\">"+esc(error)+"</div>":"")+"<section class=\"auth-grid\"><form method=\"post\" class=\"auth-card\"><input type=\"hidden\" name=\"action\" value=\"create\"><input type=\"hidden\" name=\"intent\" value=\""+esc(intent)+"\"><p class=\"kicker\">New to LegaX</p><h2>Create account</h2><label>Name<input name=\"display_name\" autocomplete=\"name\" required maxlength=\"120\"></label><label>Email<input name=\"email\" type=\"email\" autocomplete=\"email\" required></label><label>Password<input name=\"password\" type=\"password\" autocomplete=\"new-password\" minlength=\"10\" required><small>Minimum 10 characters.</small></label><label>Confirm password<input name=\"password_confirmation\" type=\"password\" autocomplete=\"new-password\" minlength=\"10\" required><small>Enter the same password again.</small></label><button type=\"submit\">Create account</button></form><form method=\"post\" class=\"auth-card\"><input type=\"hidden\" name=\"action\" value=\"signin\"><input type=\"hidden\" name=\"intent\" value=\""+esc(intent)+"\"><p class=\"kicker\">Already have an account</p><h2>Sign in</h2><label>Email<input name=\"email\" type=\"email\" autocomplete=\"email\" required></label><label>Password<input name=\"password\" type=\"password\" autocomplete=\"current-password\" required></label><button type=\"submit\">Sign in</button><a href=\"/account/recovery\">Forgot password?</a></form></section><section class=\"account-next\"><strong>Choose before you continue</strong><span>These are different domain relationships, not different account types.</span><a href=\"/join\">View all paths</a></section>";
 return renderLegaXPage({title:"Account",active:"Account",content});
}